# Generated by Django 3.2.13 on 2023-04-02 16:00

import app3_messaging.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app1_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_campagne', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('number_sent', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('number_opened', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('number_clicked', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('number_unsubscribed', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_mail_type', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('default', 'default'), ('sender', 'sender'), ('CC', 'CC'), ('CCI', 'CCI')], default='default', max_length=20)),
                ('is_shown', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntraEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_opened', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('content_text', models.TextField(default='')),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('is_support', models.BooleanField(default=False)),
                ('message_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3_messaging.conversation')),
                ('recipients', models.ManyToManyField(through='app3_messaging.Intermediate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProspectUserActive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Prospect Active',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProspectUserProfile',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Prospect Unsubscribe',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app1_base.profile',),
        ),
        migrations.CreateModel(
            name='ProfileProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('finess', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Privé non lucratif', 'Private non-profit'), ('Public', 'Public'), ('Privé commercial', 'Private commercial')], max_length=50, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=120, null=True)),
                ('dept_code', models.CharField(blank=True, max_length=10, null=True)),
                ('gestionnaire', models.CharField(blank=True, max_length=300, null=True)),
                ('info_presta', models.TextField(blank=True, null=True)),
                ('info_tarif', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('list_opened', models.ManyToManyField(blank=True, related_name='list_opened', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntraEmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d', validators=[app3_messaging.validators.validate_image])),
                ('intraemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3_messaging.intraemail')),
            ],
        ),
        migrations.AddField(
            model_name='intraemail',
            name='tags',
            field=models.ManyToManyField(to='app3_messaging.Tag'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3_messaging.intraemail'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupsProspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prospect', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='DataEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clef', models.CharField(max_length=30)),
                ('email_adress_sender', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('date_clicked', models.DateTimeField(blank=True, null=True)),
                ('date_unsubscribed', models.DateTimeField(blank=True, null=True)),
                ('is_notif', models.BooleanField(default=False)),
                ('campaign_of_mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3_messaging.campaign')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='mail_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3_messaging.createemail'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='intermediate',
            unique_together={('message', 'recipient')},
        ),
    ]
