"""
Django settings for djangoticia project.
Generated by 'django-admin startproject' using Django 1.10.
For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _
from projet.settings_clients import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# new in Django 3.2
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


ALLOWED_HOSTS = ['*']

CLASS = ['face', 'person', 'chair', 'bed', 'bicycle', 'motorcycle', 'vehicle', 'bird', 'cat', 'dog', 'fall', 'masque',
         'incorrect mask', 'no mask', 'toothbrush', ]
# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'app0_access.apps.App0Config',
    'app1_base.apps.App1Config',
    'app2_machine_learning.apps.App2Config',
    'app3_messaging.apps.App3Config',
    'app4_ehpad_base.apps.App4Config',
    'app5_ehpad_messaging.apps.App5Config',
    'app6_care.apps.App6Config',
    'app7_video.apps.App7Config',
    'app8_survey.apps.App8Config',
    'app9_personnalized_project.apps.App9Config',
    'app10_social_activities.apps.App10Config',
    'app11_quality.apps.App11Config',
    'app12_delivery.apps.App12Config',
    'app13_resident.apps.App13Config',
    'app14_profile.apps.App14Config',
    'app16_portal.apps.PortalConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'app15_calendar.apps.CalendarConfig',
    'app17_help.apps.App17HelpConfig',
]

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend', 'app1_base.utils.SuperadminAuth']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app3_messaging.middleware.middleware_msg_notif',
    'app4_ehpad_base.middleware.get_new_public_photo_form',
]

ROOT_URLCONF = 'projet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'projet.context_processors.get_domain',
                'projet.context_processors.get_facial_reco_ip',
                'projet.context_processors.checkalerts',
                ],
            'libraries': {
                'admin_utils': 'app1_base.templatetags.admin_nav_bar',
                 }
        },
    },
]
WSGI_APPLICATION = 'projet.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# Provide a lists of languages which your site supports.
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),)

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.path.join(BASE_DIR, '../static_root')

# Physical system path where the static files are stored. Files that are being uploaded by the user.
MEDIA_ROOT = os.path.join(BASE_DIR, '../media_root')

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
IMG_LOGO = STATIC_URL + "app4_ehpad_base/img/" + IMG_LOGO_NAME

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True

# Your Account SID from twilio.com/console
ACCOUNT_SID = os.getenv('ACCOUNT_SID', '')
# Your Auth Token from twilio.com/console
AUTH_TOKEN = os.getenv('AUTH_TOKEN', '')

VERSION = '2.0'

WAIT_BEFORE_DETECTION = 20
DATASET_TEST = False

PYTHON = 'python3'
USER_LANGUAGE = 'fr'
TIME_ON_CAMERA = 60  # the duration to display on live camera before stop
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN', '')
MAIL_SENDER = "contact@serenicia.fr"
MAIL_OBJECT = "Serenicia alert !!!"
SITE_ID = 1
DOMAIN = 'Serenicia'
INIT_PASS = os.getenv('INIT_PASS', '')

MASS_MAILLING_EMAIL = 'constance.martin@serenicia.net'
MASS_MAILLING_PASSWORD = os.getenv('MASS_MAILLING_PASSWORD', '')
MASS_MAILLING_SERVER = 'ssl0.ovh.net'
MASS_MAILLING_PORT = '587'


FACIAL_RECO_IP = os.getenv('FACIAL_RECO_IP', '')
FACIAL_RECO_KEY = os.getenv('FACIAL_RECO_KEY', '')

NETSOINS_URL = os.getenv('NETSOINS_URL', '')
NETSOINS_KEY = os.getenv('NETSOINS_KEY', '')
NETSOINS_TYPE = os.getenv('NETSOINS_TYPE', '')

CLIENT_CP = os.getenv('CLIENT_CP', '')
CLIENT_ADRESS = os.getenv('CLIENT_ADRESS', '')
CLIENT_CITY = os.getenv('CLIENT_CITY', '')

# 15Mo
DATA_UPLOAD_MAX_MEMORY_SIZE = None

ALEXA_KEY = os.getenv('ALEXA_KEY', '')

# ------------------------------- TINY MCE API KEY ----------------------------
TINYMCE_KEY = os.getenv('TINYMCE_KEY', '')


# --------------------------------------------------   DOCUSIGN   ------------------------------------------------------
USER_ID = os.getenv('USER_ID', '')
CLIENT_ID_DOCUSIGN = os.getenv('CLIENT_ID_DOCUSIGNY', '')

PUBLIC_KEY = os.getenv('PUBLIC_KEY', '')
PRIVATE_KEY = os.getenv('PRIVATE_KEY', '')


# Url for accept consent
STATE = os.getenv('STATE', '')
RESPONSE_TYPE = "code"
SCOPE = "signature%20impersonation"
BASE_URI = "https://account.docusign.com/oauth/auth"

# Obtain access_token
AUD = 'account.docusign.com'
GRANT_TYPE = 'urn:ietf:params:oauth:grant-type:jwt-bearer'
URL_TOKEN = 'https://account.docusign.com/oauth/token'

# Obtain account_id
URL_USER_INFO = "https://account.docusign.com/oauth/userinfo"

# Url create_api_client
URL_API_CLIENT = 'https://eu.docusign.net/restapi'

API_CALL = "https://eu.docusign.net/restapi/v2/accounts/"

# ----------------------------------------------------------------------------------------------------------------------

# ------------------------------------------------SCSS TO CSS-----------------------------------------------------------

STATICFILES_FINDERS = (

    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',

)

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

COMPRESS_OFFLINE = True
LIBSASS_OUTPUT_STYLE = 'compressed'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# --------------------------------------------------------------------------------------------------------------------
KEY_API_MAPBOX = os.getenv('KEY_API_MAPBOXY', '')
