# Generated by Django 3.2.13 on 2023-04-02 16:01

import app10_social_activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app15_calendar', '__first__'),
        ('app4_ehpad_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('new_pk', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Text')),
                ('order', models.PositiveIntegerField(default=app10_social_activities.models.get_order, unique=True, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('subject', models.CharField(choices=[('location', 'Place'), ('organizer', 'Organizer'), ('contents', 'Contents')], max_length=10, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=app10_social_activities.models.upload_photo)),
                ('activity_new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.planningevent')),
                ('identified', models.ManyToManyField(blank=True, related_name='identified', to='app4_ehpad_base.ProfileSerenicia')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'good'), (4, 'very_good')], null=True)),
                ('activity_new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.planningevent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10_social_activities.question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.profileserenicia')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=app10_social_activities.models.get_current_year, verbose_name='Year')),
                ('result', models.TextField(blank=True, help_text='For the current year', null=True, verbose_name='Results')),
                ('project', models.TextField(blank=True, help_text='For the following year', null=True, verbose_name='Project')),
                ('objectives', models.TextField(blank=True, help_text='Objectives to date', null=True, verbose_name='Objectives')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='Day')),
                ('animator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4_ehpad_base.profileserenicia', verbose_name='Animator')),
                ('event', models.ForeignKey(limit_choices_to=models.Q(('is_activity', True)), on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.event', verbose_name='Activity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app15_calendar.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Report',
                'unique_together': {('event', 'year')},
            },
        ),
    ]
