rm -rf  app15_calendar/migrations/*
rm -rf  app14_profile/migrations/*
rm -rf  app13_resident/migrations/*
rm -rf  app12_delivery/migrations/*
rm -rf  app11_quality/migrations/*
rm -rf  app10_social_activities/migrations/*
rm -rf  app9_personnalized_project/migrations/*
rm -rf  app8_survey/migrations/*
rm -rf  app7_video/migrations/*
rm -rf  app6_care/migrations/*
rm -rf  app5_ehpad_messaging/migrations/*
rm -rf  app4_ehpad_base/migrations/*
rm -rf  app3_messaging/migrations/*
rm -rf  app2_machine_learning/migrations/*
rm -rf  app1_base/migrations/*
rm -rf  app0_access/migrations/*
