# Generated by Django 3.2.13 on 2023-04-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app4_ehpad_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Entitled')),
                ('public', models.BooleanField(default=False, help_text='Select if the activity can be visible to everyone', verbose_name='Public')),
                ('is_activity', models.BooleanField(default=False)),
                ('is_visit', models.BooleanField(default=False)),
                ('is_birthday', models.BooleanField(default=False)),
                ('objective', models.TextField(blank=True, null=True, verbose_name='Objectives')),
                ('protected_unit_only', models.BooleanField(default=False, help_text='Check if this activity is intended for the protected unit', verbose_name='Protected unit')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='PlanningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Beginning')),
                ('end', models.DateTimeField(null=True, verbose_name='End')),
                ('event_comment', models.CharField(blank=True, help_text='optionnal comment', max_length=1000, verbose_name='Comment')),
                ('gg_event_id', models.CharField(max_length=100, null=True, unique=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('attendance', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'home'), ('user__groups__permissions__codename__in', ['view_residentehpad', 'view_residentrss']), ('user__is_active', True)), related_name='pl_ev_attendance_list', to='app4_ehpad_base.ProfileSerenicia')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_ev_blog_post', to='app4_ehpad_base.blogpost')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.event')),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'home'), ('user__groups__permissions__codename__in', ['view_residentehpad', 'view_residentrss']), ('user__is_active', True)), related_name='pl_ev_participants', to='app4_ehpad_base.ProfileSerenicia', verbose_name='Participants')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, help_text='Choose a recurrence start date', null=True, verbose_name='Recurrence start')),
                ('end', models.DateField(blank=True, help_text='Choose a recurrence end date', null=True, verbose_name='Recurrence end')),
                ('start_time', models.TimeField(help_text='Start of activity', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='End of the activity', verbose_name='End time')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Activity day', verbose_name='Day')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.event')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEventPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.photos')),
                ('planning_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.planningevent')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.mealbooking')),
                ('planning_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.planningevent')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app15_calendar.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(limit_choices_to=models.Q(('user__groups__permissions__codename', 'view_animation'), ('user__is_active', True)), on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='app4_ehpad_base.profileserenicia', verbose_name='Organizer'),
        ),
    ]
