# Generated by Django 3.2.13 on 2023-04-02 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('size', models.SmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ratio', models.FloatField(default=1)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('process', models.SmallIntegerField()),
                ('config', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app2_machine_learning.config')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('config', 'name')},
            },
        ),
    ]
