# Generated by Django 3.2.13 on 2023-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='docker_version',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reboot',
        ),
        migrations.RemoveField(
            model_name='client',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tunnel_port',
        ),
    ]
