# Generated by Django 3.2.13 on 2023-04-02 16:00

import app6_care.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app15_calendar', '__first__'),
        ('app1_base', '0001_initial'),
        ('app4_ehpad_base', '0001_initial'),
        ('app11_quality', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTreatmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_time', models.DateTimeField(blank=True, null=True)),
                ('intervention_time', models.DateTimeField(auto_now=True)),
                ('profession', models.CharField(choices=[('AS', 'AS'), ('ASH', 'ASH')], default='AS', max_length=3)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_treatment_plan_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_treatment_plan_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nappy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('stock_in_storehouse', models.PositiveSmallIntegerField(default=0)),
                ('maximal_total_stock', models.PositiveSmallIntegerField(default=0)),
                ('nappies_per_bag', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('bags_per_box', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_box', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_security', models.DecimalField(decimal_places=2, default=1.1, help_text='order = consumption_next_7_days * order_security', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('svg_path', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/nappies/NAME.svg', max_length=200, null=True)),
                ('svg_path_new', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/nappies/NAME.svg', max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserNappy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nappy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6_care.nappy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('nappy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.nappy')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TmpInterventionTreatmentPlanForWebsocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField()),
                ('intervention_treatment_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app6_care.interventiontreatmentplan')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLevel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('svg_path', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('svg_path_new', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('shared_with_family', models.BooleanField(default=False)),
                ('to_be_transmitted', models.BooleanField(default=True)),
                ('visible_by', models.CharField(blank=True, choices=[('Woman', 'Woman'), ('Man', 'Man')], default=None, max_length=5, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('care_plan', models.BooleanField(default=False)),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app11_quality.protocol_list')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('svg_path', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('svg_path_new', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('shared_with_family', models.BooleanField(default=False)),
                ('to_be_transmitted', models.BooleanField(default=True)),
                ('visible_by', models.CharField(blank=True, choices=[('Woman', 'Woman'), ('Man', 'Man')], default=None, max_length=5, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('care_plan', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('details', models.ManyToManyField(blank=True, to='app6_care.TaskLevel4')),
                ('nappy', models.ManyToManyField(blank=True, to='app6_care.Nappy')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app11_quality.protocol_list')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('svg_path', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('svg_path_new', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('shared_with_family', models.BooleanField(default=False)),
                ('to_be_transmitted', models.BooleanField(default=True)),
                ('visible_by', models.CharField(blank=True, choices=[('Woman', 'Woman'), ('Man', 'Man')], default=None, max_length=5, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('care_plan', models.BooleanField(default=False)),
                ('details', models.ManyToManyField(blank=True, related_name='match_btw_task_level_2_and_3', to='app6_care.TaskLevel3')),
                ('nappy', models.ManyToManyField(blank=True, to='app6_care.Nappy')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app11_quality.protocol_list')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('svg_path', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('svg_path_new', models.CharField(blank=True, default='app4_ehpad_base/img/homemade_svg/NAME_64x64.svg', max_length=200, null=True)),
                ('profession', models.CharField(choices=[('AS', 'AS'), ('ASH', 'ASH')], default='AS', max_length=3)),
                ('specific_to_a_resident', models.BooleanField(default=True)),
                ('care_plan', models.BooleanField(default=True)),
                ('color', models.CharField(default=app6_care.models.random_color, max_length=7)),
                ('details', models.ManyToManyField(blank=True, to='app6_care.TaskLevel2')),
                ('nappy', models.ManyToManyField(blank=True, to='app6_care.Nappy')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app11_quality.protocol_list')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInTreatmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in_cycle', models.IntegerField(choices=[(1, 'Week 1 - Monday'), (2, 'Week 1 - Tuesday'), (3, 'Week 1 - Wednesday'), (4, 'Week 1 - Thursday'), (5, 'Week 1 - Friday'), (6, 'Week 1 - Saturday'), (7, 'Week 1 - Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('task_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel2')),
                ('task_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel3')),
                ('task_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel4')),
                ('treatments_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6_care.treatmentsplan')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1500)),
                ('related_task_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel2')),
                ('related_task_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel3')),
                ('related_task_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel4')),
            ],
        ),
        migrations.CreateModel(
            name='SectorNappy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('nappy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6_care.nappy')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_base.subsector')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='nappy',
            name='sector',
            field=models.ManyToManyField(blank=True, through='app6_care.SectorNappy', to='app1_base.SubSector'),
        ),
        migrations.AddField(
            model_name='nappy',
            name='user',
            field=models.ManyToManyField(blank=True, through='app6_care.UserNappy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventiontreatmentplan',
            name='treatment_plan_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6_care.taskintreatmentplan'),
        ),
        migrations.CreateModel(
            name='InterventionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nappy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.nappy')),
                ('task_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel2')),
                ('task_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel3')),
                ('task_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel4')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_to_a_resident', models.BooleanField(default=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('transmitted', models.BooleanField(default=False)),
                ('profession', models.CharField(choices=[('AS', 'AS'), ('ASH', 'ASH')], default='AS', max_length=3)),
                ('from_care_plan', models.BooleanField(default=False)),
                ('lvl1_inter_id', models.IntegerField(blank=True, null=True)),
                ('details', models.ManyToManyField(blank=True, to='app6_care.InterventionDetail')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('task_comment', models.ManyToManyField(blank=True, to='app6_care.TaskComment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel1')),
            ],
        ),
        migrations.CreateModel(
            name='FreeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('profession', models.CharField(choices=[('AS', 'AS'), ('ASH', 'ASH')], default='AS', max_length=3)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_comment_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_comment_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarePlanEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl1_inter_id', models.IntegerField(blank=True, null=True)),
                ('planning_event_new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app15_calendar.planningevent')),
                ('task_lvl_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel1')),
                ('task_lvl_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel2')),
                ('task_lvl_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel3')),
                ('task_lvl_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6_care.tasklevel4')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.profileserenicia')),
                ('tasks', models.ManyToManyField(to='app6_care.CarePlanEvent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usernappy',
            constraint=models.UniqueConstraint(fields=('user', 'nappy'), name='a user and a nappy are unique together'),
        ),
        migrations.AddConstraint(
            model_name='sectornappy',
            constraint=models.UniqueConstraint(fields=('sector', 'nappy'), name='a sector and a nappy are unique together'),
        ),
    ]
