# Generated by Django 3.2.13 on 2023-04-02 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app4_ehpad_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampApplicationPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(choices=[('pa', 'PA'), ('pha', 'PHA'), ('phe', 'PHE'), ('pds', 'PDS'), ('ahi', 'AHI'), ('pe-pjj', 'PE-PJJ')], max_length=20, verbose_name='Public')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Order')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Chapter',
            },
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('exigence', models.CharField(choices=[('standard', 'Standard'), ('imperative', 'Imperative')], max_length=20, verbose_name='Requirement level')),
                ('essms', models.CharField(choices=[('essms', 'All ESSMS'), ('social', 'Social'), ('medicosocial', 'Medico-social')], max_length=20, verbose_name='ESSMS')),
                ('structure', models.CharField(choices=[('structures', 'All structures'), ('etablissement', 'Establishment'), ('service', 'Service')], max_length=20, verbose_name='Structure')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.chapitre', verbose_name='Chapter')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.profileserenicia', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Criterion',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='protocol_images/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Goal',
            },
        ),
        migrations.CreateModel(
            name='Protocol_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='protocol_list/', verbose_name='File')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(choices=[('globales', 'HAS - Global'), ('specifiques', 'HAS – specific'), ('references', 'Legal and regulatory references'), ('autresreferences', 'Other references')], max_length=20, verbose_name='Reference')),
                ('detail', models.CharField(max_length=300, verbose_name='Detail')),
                ('reference_url', models.CharField(max_length=500, verbose_name='Url reference')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ManyToManyField(to='app11_quality.Image', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TempMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app11_quality.room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4_ehpad_base.profileserenicia')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.critere', verbose_name='Criterion')),
                ('protocols', models.ManyToManyField(to='app11_quality.Protocol_list', verbose_name='Protocol')),
            ],
        ),
        migrations.AddField(
            model_name='protocol_list',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app11_quality.Tag', verbose_name='Flag'),
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('generic', 'Generic'), ('specific', 'Specific')], max_length=15, verbose_name='Category')),
                ('title', models.ManyToManyField(blank=True, to='app11_quality.Title', verbose_name='Content of the protocol')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Elementsevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('entretienpersonne', 'Interview with the person'), ('entretienpro', 'Interview with the professionals'), ('entretiencsv', 'Interview with CVS members'), ('entretienessms', 'Interview with the ESSMS'), ('consultationdoc', 'Document consultation'), ('observation', 'Observation')], max_length=20, verbose_name='Elements of evaluation')),
                ('detail', models.CharField(max_length=500, verbose_name='Detail')),
                ('evaluation', models.IntegerField(choices=[(0, 'In progress'), (1, 'Not at all satisfactory'), (2, 'Rather unsatisfactory'), (3, 'Quite satisfying'), (4, 'Quite satisfactory'), (5, 'Optimized')], default=0)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.critere', verbose_name='Criterion')),
            ],
        ),
        migrations.AddField(
            model_name='critere',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.objectif', verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='critere',
            name='public',
            field=models.ManyToManyField(to='app11_quality.ChampApplicationPublic', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='critere',
            name='reference',
            field=models.ManyToManyField(to='app11_quality.References', verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='critere',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11_quality.thematique', verbose_name='Thematic'),
        ),
    ]
